services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: mohdrzu
      POSTGRES_PASSWORD: mohdrzu
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    container_name: ms_mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: mohdrzu
      MONGO_INITDB_ROOT_PASSWORD: mohdrzu

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080 # UI
      - 1025:1025 # SMTP Server

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  mongo: